#!/usr/bin/env bash
# this script is used to dig input domain and subdomains if given
# else  ping all 4 sub domains www, lb-01, web-01 and web-02 in this order
format_answer () {
	printf "The subdomain %s is a " "$2"
	dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $4 }'
	printf " record and points to "
	dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $5 }'
	echo ""
}

if [[ $# -eq 2 ]]; then
	format_answer "$1" "$2"
else
	subdomains=("www" "lb-01" "web-01" "web-02")
	for sub in "${subdomains[@]}"; do
		format_answer "$1" "$sub"
	done
fi
