#!/usr/bin/env bash
# sets up the firewall via ufw
echo y | sudo ufw reset
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
echo y | sudo ufw enable
