#!/bin/bash

# Kill any processes on port 5000
echo "Killing any processes on port 5000..."
sudo lsof -t -i :5000 | xargs sudo kill -9

# Start services in tmux sessions

# Start services for AirBnB_clone_v2
echo "Starting services for AirBnB_clone_v2..."
cd ~/AirBnB_clone_v2
tmux new-session -d -s airbnb_clone_v2_hello 'gunicorn --bind 0.0.0.0:5000 web_flask.0-hello_route:app'
tmux new-session -d -s airbnb_clone_v2_number 'gunicorn --bind 0.0.0.0:5001 web_flask.6-number_odd_or_even:app'

# Start API service for AirBnB_clone_v3
echo "Starting API service for AirBnB_clone_v3..."
cd ~/AirBnB_clone_v3
tmux new-session -d -s airbnb_clone_v3_api 'gunicorn --bind 0.0.0.0:5002 api.v1.app:app'

# Start dynamic web service for AirBnB_clone_v4
echo "Starting dynamic web service for AirBnB_clone_v4..."
cd ~/AirBnB_clone_v4
tmux new-session -d -s airbnb_clone_v4_dynamic 'gunicorn --bind 0.0.0.0:5003 web_dynamic.2-hbnb:app'

echo "All services have been started."
